### ISSUE TITLE
can't registered.

### ISSUE THREAD

**Issue by 625781186** [nikifkon/ChatApp#8]
![image](https://user-images.githubusercontent.com/30521429/71405793-67a13700-2671-11ea-8f46-1a57c3f22d67.png)

**Comment by nikifkon-old** [comment]
Hello, 
Can You provide more info about this POST request, what is response you got, what is post data sent?
In my case, this request is successed.
May be you did some actions before sing up, that can be caused of this bug?

**Comment by 625781186** [comment]
> Hello,
> Can You provide more info about this POST request, what is response you got, what is post data sent?
> In my case, this request is successed.
> May be you did some actions before sing up, that can be caused of this bug?

Sorry , it's ok after I disbale  cache .
